### ISSUE TITLE
Week 4: One Cat is not enough Meow

### ISSUE THREAD

**Issue by ganning127** [ganning127/dsfasdf#2]
Week 4 Step 6 ⬤⬤⬤⬤⬤⬤◯ | 🕐 Estimated completion: 5-20 minutes

## One Cat isn't enough ~ Meow

*Now that we've got a frontend that can only return one picture, let's take it to the next level and return FOUR pictures at the same time. To do this, let's edit our old twoCatz function.*

### ✅  Task:
- [ ] Make sure you're on the `twocatz-frontend` branch
- [ ] Edit your twoCATZ HTTP Trigger from Week 1 so it takes in 4 parameters (`name1`, `name2`, `name3`, `name4`) and returns four pictures **in base64** with the parameters.
- [ ] Remove the "random name" feature in your Azure Function
- [ ] Commit `twocatz/index.js` and test your result with Postman

### ❗Requirements
- Make sure you encode the pictures in **base64**
- Make sure your parameters are named correctly!
- The Function URL should still be in your `TWOCATZ_ENDPOINT` secret since you are **editing the same function**

### 🚧 Test your Work
Open up **Postman** again since we are testing an API.

⚠️ Make a GET request with the four name parameters. Do you get a JSON object containing `name1`, `name2`, `name3`, and `name4` attributes encoded in base64?

> :bulb: Having trouble? Look back to old branches - these skills were all used before!

**Comment by ganning127** [comment]
closed via oauth
